import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/navbar'
import Repository from '../../repository/strapi_repo'
import { useRouter } from 'next/router'
import Post from '../../model/Post'
import Card from '../../component/card'
import Intl from '../../../i18n/intl'
import { useEffect, useState } from 'react'


export async function getStaticPaths() {
    const locales = ['mk', 'en']
    const paths = locales.map((locale) => ({ params: { locale: locale }}))
    console.log("paths: ", paths)
    return { paths, fallback: false}
}

export async function getStaticProps({ params }: { params: { locale : string }}) {
    const locale = params.locale
    console.log("locale: ", locale)
    return { props: { locale: locale } }
}


export default function Home(props :  {locale: string} ){
    console.log("props: ", props)

    const repository = new Repository()
    const router = useRouter()
    const translation = new Intl();
    const t  = (key: string) => translation.getTranslation(props.locale ? props.locale : 'mk', key);
    const [architecturePosts, setArchitecturePosts] = useState<Post[]>([])
    const [hydrotechnicsPosts, setHydrotechnicsPosts] = useState<Post[]>([])

    const locale = props.locale
    useEffect(() => {
        repository.getArchitecturalProjects(props.locale).then(posts => {
            setArchitecturePosts(posts)
        })
        repository.getHydrotechnicalProjects(props.locale).then(posts => {
            setHydrotechnicsPosts(posts)
        })
    }, [locale])



    const navigateToProject = (id: number) => {
        router.push(props.locale + '/project/'+ id)
    }

    useEffect(() => {
        if(translation.readLocale() !== props.locale){
            router.push(props.locale)
        }
    }, [])


    return (
        <>
            <Head>
                <title>{t("company-name")}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={'container d-flex flex-column justify-content-between'}>
                <div className='my-5'>
                    <h2 className='h2 text-dark'>{t("architecture")}</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {architecturePosts.map(post => (
                            <Card key={post.id} post={post} onClick={() => navigateToProject(post.id)}/>
                        ))}
                    </div>
                </div>
                <div className='my-5'>
                    <h2 className='h2 text-dark'>{t("hydrotechnics")}</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {hydrotechnicsPosts.map(post => (
                            <Card key={post.id} post={post} onClick={() => navigateToProject(post.id)}/>
                        ))}
                    </div>
                </div>
            </main>
        </>
    )
}
