import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/navbar'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const posts = [
        {
            id: 1,
            title: 'Проект 1',
            imageUrl: '/images/proekt1.png'
        },
        {
            id: 2,
            title: 'Проект 2',
            imageUrl: '/images/proekt1.png'
        },
        {
            id: 3,
            title: 'Проект 3',
            imageUrl: '/images/proekt1.png'
        },
        {
            id: 4,
            title: 'Проект 4',
            imageUrl: '/images/proekt1.png'
        },
        {
            id: 5,
            title: 'Проект 5',
            imageUrl: '/images/proekt1.png'
        },
        {
            id: 6,
            title: 'Проект 6',
            imageUrl: '/images/proekt1.png'
        }
    ]


    return (
        <>
            <Head>
                <title>АКВА-ИНГ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={'container d-flex flex-column justify-content-around'}>
                <div className='mt-3'>
                    <h2 className='h2 text-dark'>АРХИТЕКТУРА</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {posts.map(post => (
                            <div className='card project-card flex-shrink-0 me-1' key={post.id}>
                                <img src={post.imageUrl} className='card-img' alt={post.title} />
                                <div className='card-img-overlay d-flex flex-column justify-content-end'>
                                    <h5 className='card-title'>{post.title}</h5>
                                    <p className='card-text'>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
                <div className='mt-3'>
                    <h2 className='h2 text-dark'>ХИДРОТЕХНИКА</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {posts.map(post => (
                            <div className='card project-card flex-shrink-0 me-1' key={post.id}>
                                <img src={post.imageUrl} className='card-img' alt={post.title} />
                                <div className='card-img-overlay d-flex flex-column justify-content-end'>
                                    <h5 className='card-title'>{post.title}</h5>
                                    <p className='card-text'>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    )
}
