import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/navbar'
import Repository from '../repository/repo'
import { useRouter } from 'next/router'
import Post from '../component/card'
import Card from '../component/card'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const repository = new Repository()
    const posts = repository.getAllPosts()
    const router = useRouter()

    const navigateToProject = (id: number) => {
        router.push('/project/' + id)
    }


    return (
        <>
            <Head>
                <title>АКВА-ИНГ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={'container d-flex flex-column justify-content-around'}>
                <div className='mt-3'>
                    <h2 className='h2 text-dark'>АРХИТЕКТУРА</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {posts.map(post => (
                            <Card post={post} onClick={() => navigateToProject(post.id)}/>
                        ))}
                    </div>
                </div>
                <div className='mt-3'>
                    <h2 className='h2 text-dark'>ХИДРОТЕХНИКА</h2>
                    <div className='card-container d-flex flex-row justify-content-start overflow-auto'>
                        {posts.map(post => (
                            <Card post={post} onClick={() => navigateToProject(post.id)}/>
                        ))}
                    </div>
                </div>
            </main>
        </>
    )
}
